# Generated by Django 4.0.3 on 2022-04-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaigodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaigodo', models.CharField(max_length=4)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouKaigoDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youkaigodo_nyuuryokuDate', models.DateField()),
                ('nintei_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('kaigodo', models.ForeignKey(db_column='kaigodo', on_delete=django.db.models.deletion.PROTECT, to='hana_cm.kaigodo')),
                ('riyousha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Youkaigodo_riyousha', to='hana_cm.riyousha')),
            ],
        ),
        migrations.AddConstraint(
            model_name='youkaigodo',
            constraint=models.UniqueConstraint(fields=('riyousha', 'youkaigodo_nyuuryokuDate'), name='riyousha_date_unique'),
        ),
    ]
