# Generated by Django 4.0.3 on 2022-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0002_kaigodo_youkaigodo_youkaigodo_riyousha_date_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='youkaigodo',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
