# Generated by Django 4.0.3 on 2022-04-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0003_youkaigodo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youkaigodo',
            name='slug',
        ),
    ]
