# Generated by Django 4.0.3 on 2022-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0004_remove_youkaigodo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyousha',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
